/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.EspaciosFisicosThis;
import persistence.EspaciosFisicosDAO;

/**
 *
 * @author 52551
 */
public class EspaciosFisicos extends javax.swing.JFrame {

    private int capacidadPersonas = 0;
    private final EspaciosFisicosDAO dao = new EspaciosFisicosDAO();
    /**
     * Creates new form EspaciosFisicos
     */
    public EspaciosFisicos() {
        initComponents();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
        btnIncrementarG.addActionListener(this::btnIncrementarGActionPerformed);
        btnDisminuirG.addActionListener(this::btnDisminuirGActionPerformed);
    
        cargarClasesPlanificadas();
        actualizarCapacidad();
    }
    
    private void cargarClasesPlanificadas() {
    Map<String, String> clases = dao.obtenerClasesPlanificadas();
    DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();
    
    modelo.addElement("Dojo Fénix");
    
    clases.keySet().forEach(modelo::addElement);
    
    cmbTipoEspacio.setModel(modelo);
    
    cmbTipoEspacio.addActionListener(e -> {
        txtCaracteristicas.setText("Por el momento no hay reporte que se tenga que enviar");
    });
    
    txtCaracteristicas.setText("Por el momento no hay reporte que se tenga que enviar");
}
    
    private void actualizarCapacidad() {
        lblCapacidadPersonas.setText(String.valueOf(capacidadPersonas));
    }
    
    private void btnIncrementarGActionPerformed(java.awt.event.ActionEvent evt) {                                               
        capacidadPersonas++;
        actualizarCapacidad();
    }                                              

    private void btnDisminuirGActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (capacidadPersonas > 0) {
        capacidadPersonas--;
        actualizarCapacidad();
        }
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbTipoEspacio = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCaracteristicas = new javax.swing.JTextArea();
        btnCancelarGestion = new javax.swing.JButton();
        btnGuardarGestion = new javax.swing.JButton();
        btnIncrementarG = new javax.swing.JButton();
        btnDisminuirG = new javax.swing.JButton();
        lblCapacidadPersonas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 162, 39));

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(73, 80, 87));
        jLabel1.setText("Gestión de Espacios Físicos");

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(73, 80, 87));
        jLabel5.setText("Tipo de Espacio");

        cmbTipoEspacio.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 80, 87));
        jLabel6.setText("Capacidad de Personas");

        jLabel13.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(73, 80, 87));
        jLabel13.setText("Características del Espacio");

        txtCaracteristicas.setColumns(20);
        txtCaracteristicas.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        txtCaracteristicas.setRows(5);
        jScrollPane1.setViewportView(txtCaracteristicas);

        btnCancelarGestion.setBackground(new java.awt.Color(255, 10, 84));
        btnCancelarGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarGestion.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarGestion.setText("Cancelar");
        btnCancelarGestion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelarGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarGestionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarGestionMouseEntered(evt);
            }
        });
        btnCancelarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarGestionActionPerformed(evt);
            }
        });

        btnGuardarGestion.setBackground(new java.awt.Color(72, 202, 228));
        btnGuardarGestion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardarGestion.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarGestion.setText("Guardar");
        btnGuardarGestion.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarGestion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarGestion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarGestionMouseClicked(evt);
            }
        });
        btnGuardarGestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarGestionActionPerformed(evt);
            }
        });

        btnIncrementarG.setBackground(new java.awt.Color(247, 127, 0));
        btnIncrementarG.setForeground(new java.awt.Color(255, 255, 255));
        btnIncrementarG.setText("Ʌ");
        btnIncrementarG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIncrementarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncrementarGActionPerformed(evt);
            }
        });

        btnDisminuirG.setBackground(new java.awt.Color(247, 127, 0));
        btnDisminuirG.setForeground(new java.awt.Color(255, 255, 255));
        btnDisminuirG.setText("V");
        btnDisminuirG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblCapacidadPersonas.setFont(new java.awt.Font("STXihei", 1, 18)); // NOI18N
        lblCapacidadPersonas.setForeground(new java.awt.Color(221, 221, 221));
        lblCapacidadPersonas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCapacidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDisminuirG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnIncrementarG)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(cmbTipoEspacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(lblCapacidadPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnIncrementarG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDisminuirG)))
                .addGap(46, 46, 46)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarGestionActionPerformed
        if (cmbTipoEspacio.getSelectedItem() == null || txtCaracteristicas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Complete todos los campos obligatorios", 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
            return;
        }

        EspaciosFisicosThis espacio = new EspaciosFisicosThis(
            (String) cmbTipoEspacio.getSelectedItem(),
            capacidadPersonas,
            txtCaracteristicas.getText()
        );
        
        dao.guardarEspacio(espacio);
    }//GEN-LAST:event_btnGuardarGestionActionPerformed

    private void btnCancelarGestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarGestionActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarGestionActionPerformed
/*
    private void btnIncrementarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncrementarGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIncrementarGActionPerformed
*/
    private void btnCancelarGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarGestionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarGestionMouseClicked

    private void btnCancelarGestionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarGestionMouseEntered
        JOptionPane.showMessageDialog(null, "Botón bloqueado por falla en pruebas");
    }//GEN-LAST:event_btnCancelarGestionMouseEntered

    private void btnGuardarGestionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarGestionMouseClicked
        JOptionPane.showMessageDialog(null, "Botón no funcional por falla en pruebas");
    }//GEN-LAST:event_btnGuardarGestionMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EspaciosFisicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EspaciosFisicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EspaciosFisicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaciosFisicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EspaciosFisicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarGestion;
    private javax.swing.JButton btnDisminuirG;
    private javax.swing.JButton btnGuardarGestion;
    private javax.swing.JButton btnIncrementarG;
    private javax.swing.JComboBox<String> cmbTipoEspacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCapacidadPersonas;
    private javax.swing.JTextArea txtCaracteristicas;
    // End of variables declaration//GEN-END:variables
}
