
package igu;

import java.awt.Color;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistence.CatalogosDAO;
import persistence.EvolucionEstudianteDAO;

/**
 *
 * @author 52551
 */
public class EvolucionEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form EvolucionEstudiante
     */
    public EvolucionEstudiante() {
        initComponents();
        cargarCombos();
        configurarTabla();
        this.setLocationRelativeTo(this);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dtFechaIngreso = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cmbRangoActual = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarEstudiante = new javax.swing.JTextField();
        lblIconCalendar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnBuscarEstudiante = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEvoEstudiante = new javax.swing.JTable();
        btnCancelarEvo = new javax.swing.JButton();
        btnGuardarEvo = new javax.swing.JButton();
        cmbEstado = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(201, 162, 39));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("STXihei", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 249, 255));
        jLabel1.setText("Evolución de Estudiante");

        jLabel5.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Fecha de Ingreso");

        dtFechaIngreso.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Rango Actual");

        cmbRangoActual.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N
        cmbRangoActual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbRangoActualMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Estado");

        txtBuscarEstudiante.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N

        lblIconCalendar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnBuscarEstudiante.setBackground(new java.awt.Color(247, 127, 0));
        btnBuscarEstudiante.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnBuscarEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEstudiante.setText("Buscar");
        btnBuscarEstudiante.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuscarEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarEstudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarEstudianteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarEstudianteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarEstudianteMouseExited(evt);
            }
        });
        btnBuscarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarEstudianteActionPerformed(evt);
            }
        });

        tblEvoEstudiante.setBackground(new java.awt.Color(0, 8, 20));
        tblEvoEstudiante.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tblEvoEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        tblEvoEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nombre", "App", "Apm", "Nacimiento", "Ingreso", "Rango", "Estado", "Foto"
            }
        ));
        jScrollPane1.setViewportView(tblEvoEstudiante);
        if (tblEvoEstudiante.getColumnModel().getColumnCount() > 0) {
            tblEvoEstudiante.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        btnCancelarEvo.setBackground(new java.awt.Color(255, 10, 84));
        btnCancelarEvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarEvo.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelarEvo.setText("Cancelar");
        btnCancelarEvo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelarEvo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelarEvo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarEvoMouseEntered(evt);
            }
        });
        btnCancelarEvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEvoActionPerformed(evt);
            }
        });

        btnGuardarEvo.setBackground(new java.awt.Color(72, 202, 228));
        btnGuardarEvo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGuardarEvo.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarEvo.setText("Guardar");
        btnGuardarEvo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGuardarEvo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardarEvo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEvoActionPerformed(evt);
            }
        });

        cmbEstado.setFont(new java.awt.Font("STXihei", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(dtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIconCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(cmbRangoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(31, 31, 31))
                                    .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(126, 126, 126))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCancelarEvo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardarEvo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dtFechaIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbRangoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblIconCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEvo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardarEvo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarEvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEvoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCancelarEvoActionPerformed

    private void btnGuardarEvoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEvoActionPerformed
        EvolucionEstudianteDAO metodoEvoEstudiante = new EvolucionEstudianteDAO();
        metodoEvoEstudiante.guardarEvolucionEstudiante();
    }//GEN-LAST:event_btnGuardarEvoActionPerformed

    private void btnBuscarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteActionPerformed
        String busqueda = txtBuscarEstudiante.getText().trim();

    if (busqueda.isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Ingrese un nombre o apellido para buscar", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE);
        txtBuscarEstudiante.requestFocus();
        return;
    }

    try {
        EvolucionEstudianteDAO dao = new EvolucionEstudianteDAO();
        List<Object[]> resultados = dao.buscarEstudiantes(busqueda);

        if (resultados.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "No se encontraron estudiantes con: '" + busqueda + "'", 
                "Resultados", 
                JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        DefaultTableModel modelo = (DefaultTableModel) tblEvoEstudiante.getModel();
        modelo.setRowCount(0);

        for (Object[] fila : resultados) {
            ImageIcon foto = (fila[8] != null) ? procesarFoto(fila[8]) : null;
            
            modelo.addRow(new Object[]{
                fila[0], 
                fila[1], 
                fila[2],
                fila[3],
                formatearFecha(fila[4]),
                formatearFecha(fila[5]), 
                fila[6], 
                fila[7],
                foto   
            });
        }

        ajustarAnchoColumnas();
        
        if (tblEvoEstudiante.getColumnCount() > 8) {
            tblEvoEstudiante.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
        }

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this,
            "Error al realizar la búsqueda: " + ex.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btnBuscarEstudianteActionPerformed

    private void cmbRangoActualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbRangoActualMouseClicked
        JOptionPane.showMessageDialog(null, "Función no disponible en esta versión");
    }//GEN-LAST:event_cmbRangoActualMouseClicked

    private void btnCancelarEvoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarEvoMouseEntered
        JOptionPane.showMessageDialog(null, "Botón bloqueado por falla en pruebas");
    }//GEN-LAST:event_btnCancelarEvoMouseEntered

    private void btnBuscarEstudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarEstudianteMouseClicked

    private void btnBuscarEstudianteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteMouseEntered
        btnBuscarEstudiante.setBackground(new Color(154, 3, 30));
    }//GEN-LAST:event_btnBuscarEstudianteMouseEntered

    private void btnBuscarEstudianteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarEstudianteMouseExited
        btnBuscarEstudiante.setBackground(new Color(247,127,0));
    }//GEN-LAST:event_btnBuscarEstudianteMouseExited

    
    private void configurarTabla() {
    DefaultTableModel modelo = new DefaultTableModel(
        new Object[][]{},
        new String[]{"Id", "Nombre", "App", "Apm", "Nacimiento", "Ingreso", "Rango", "Estado", "Foto"}
    ) {
        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return columnIndex == 8 ? ImageIcon.class : Object.class;
        }
    };
    
    tblEvoEstudiante.setModel(modelo);
    
    // Configuramos el renderizador para la columna de foto
    tblEvoEstudiante.getColumnModel().getColumn(8).setCellRenderer(new ImageRenderer());
    
    tblEvoEstudiante.getColumnModel().getColumn(0).setPreferredWidth(40);  
    tblEvoEstudiante.getColumnModel().getColumn(8).setPreferredWidth(120);
}
    
    private void cargarCombos() {
        EvolucionEstudianteDAO dao = new EvolucionEstudianteDAO();
        
        for (String estadoActivo : dao.obtenerEstadoActivo()) {
            cmbEstado.addItem(estadoActivo);
        }
    }
    
    private ImageIcon procesarFoto(Object fotoData) {
    if (fotoData == null) {
        return null;
    }
    
    try {
        byte[] bytes = (byte[]) fotoData;
        ImageIcon fotoOriginal = new ImageIcon(bytes);
        Image imagenEscalada = fotoOriginal.getImage()
            .getScaledInstance(80, 100, Image.SCALE_SMOOTH);
        return new ImageIcon(imagenEscalada);
    } catch (Exception e) {
        System.err.println("Error al procesar imagen: " + e.getMessage());
        return null;
    }
}
    
    private String formatearFecha(Object fecha) {
    if (fecha == null) {
        return "No registrada";
    }
    return fecha.toString(); 
}
    
    private void ajustarAnchoColumnas() {
    tblEvoEstudiante.getColumnModel().getColumn(0).setPreferredWidth(50); 
    tblEvoEstudiante.getColumnModel().getColumn(1).setPreferredWidth(120); 
    tblEvoEstudiante.getColumnModel().getColumn(2).setPreferredWidth(120); 
    tblEvoEstudiante.getColumnModel().getColumn(3).setPreferredWidth(120); 
    tblEvoEstudiante.getColumnModel().getColumn(4).setPreferredWidth(100); 
    tblEvoEstudiante.getColumnModel().getColumn(5).setPreferredWidth(100); 
    tblEvoEstudiante.getColumnModel().getColumn(6).setPreferredWidth(100);
    tblEvoEstudiante.getColumnModel().getColumn(7).setPreferredWidth(80);  
    tblEvoEstudiante.getColumnModel().getColumn(8).setPreferredWidth(100); 
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EvolucionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EvolucionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EvolucionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EvolucionEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EvolucionEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarEstudiante;
    private javax.swing.JButton btnCancelarEvo;
    private javax.swing.JButton btnGuardarEvo;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbRangoActual;
    private com.toedter.calendar.JDateChooser dtFechaIngreso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblIconCalendar;
    private javax.swing.JTable tblEvoEstudiante;
    private javax.swing.JTextField txtBuscarEstudiante;
    // End of variables declaration//GEN-END:variables
}
