
package igu;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JScrollPane;

/**
 *
 * @author 52551
 */
public class InicioDashboard extends javax.swing.JFrame {
    
    Image imagenCobraKai = Toolkit.getDefaultToolkit().createImage("D:\\CobraKaiDev\\src\\main\\java\\igu\\logo.png");
    
    /**
     * Creates new form InicioDashboard
     */
    public InicioDashboard() {
        initComponents();
        setExtendedState(InicioDashboard.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        imagenCobraKai = imagenCobraKai.getScaledInstance(757, 685, 1);
        this.lblImagenCobra.setIcon(new ImageIcon(imagenCobraKai));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDashboard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnIntoRegistro = new javax.swing.JButton();
        btnIntoEvolucionEstudiante = new javax.swing.JButton();
        btnIntoAdministracion = new javax.swing.JButton();
        btnIntoPlanificacion = new javax.swing.JButton();
        btnIntoGestionEspacios = new javax.swing.JButton();
        btnIntoEvaluacionRango = new javax.swing.JButton();
        btnIntoGestionTorneo = new javax.swing.JButton();
        btnIntoFinanzas = new javax.swing.JButton();
        btnIntoControlDisciplinario = new javax.swing.JButton();
        btnIntoEstadistica = new javax.swing.JButton();
        btnIntoGestionArchivos = new javax.swing.JButton();
        lblImagenCobra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelDashboard.setBackground(new java.awt.Color(201, 162, 39));
        panelDashboard.setBorder(javax.swing.BorderFactory.createTitledBorder("Inicio Dashboard"));

        jPanel2.setBackground(new java.awt.Color(201, 162, 39));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnIntoRegistro.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoRegistro.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoRegistro.setText("Registro Usuario");
        btnIntoRegistro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoRegistroActionPerformed(evt);
            }
        });

        btnIntoEvolucionEstudiante.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoEvolucionEstudiante.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoEvolucionEstudiante.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoEvolucionEstudiante.setText("Evolución Estudiante");
        btnIntoEvolucionEstudiante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoEvolucionEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoEvolucionEstudianteActionPerformed(evt);
            }
        });

        btnIntoAdministracion.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoAdministracion.setFont(new java.awt.Font("STXihei", 1, 10)); // NOI18N
        btnIntoAdministracion.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoAdministracion.setText("Administración de Instructores");
        btnIntoAdministracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoAdministracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoAdministracionActionPerformed(evt);
            }
        });

        btnIntoPlanificacion.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoPlanificacion.setFont(new java.awt.Font("STXihei", 1, 10)); // NOI18N
        btnIntoPlanificacion.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoPlanificacion.setText("Planificación de Clases");
        btnIntoPlanificacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoPlanificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoPlanificacionActionPerformed(evt);
            }
        });

        btnIntoGestionEspacios.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoGestionEspacios.setFont(new java.awt.Font("STXihei", 1, 10)); // NOI18N
        btnIntoGestionEspacios.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoGestionEspacios.setText("Gestión de Espacios Físicos");
        btnIntoGestionEspacios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoGestionEspacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoGestionEspaciosActionPerformed(evt);
            }
        });

        btnIntoEvaluacionRango.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoEvaluacionRango.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoEvaluacionRango.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoEvaluacionRango.setText("Evaluación Rango");
        btnIntoEvaluacionRango.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoEvaluacionRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoEvaluacionRangoActionPerformed(evt);
            }
        });

        btnIntoGestionTorneo.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoGestionTorneo.setFont(new java.awt.Font("STXihei", 1, 10)); // NOI18N
        btnIntoGestionTorneo.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoGestionTorneo.setText("Gestión de Torneo y Eventos");
        btnIntoGestionTorneo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIntoGestionTorneo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntoGestionTorneoActionPerformed(evt);
            }
        });

        btnIntoFinanzas.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoFinanzas.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoFinanzas.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoFinanzas.setText("Finanzas");
        btnIntoFinanzas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIntoControlDisciplinario.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoControlDisciplinario.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoControlDisciplinario.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoControlDisciplinario.setText("Control Disciplinario");
        btnIntoControlDisciplinario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIntoEstadistica.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoEstadistica.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoEstadistica.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoEstadistica.setText("Estadística");
        btnIntoEstadistica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnIntoGestionArchivos.setBackground(new java.awt.Color(0, 0, 0));
        btnIntoGestionArchivos.setFont(new java.awt.Font("STXihei", 1, 12)); // NOI18N
        btnIntoGestionArchivos.setForeground(new java.awt.Color(255, 255, 255));
        btnIntoGestionArchivos.setText("Gestión de Archivos");
        btnIntoGestionArchivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIntoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntoEvolucionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIntoAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIntoEvaluacionRango, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntoFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnIntoGestionArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIntoControlDisciplinario, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntoEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnIntoGestionEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnIntoGestionTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntoEvolucionEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntoAdministracion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntoPlanificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntoGestionTorneo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntoGestionEspacios, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntoFinanzas, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntoEvaluacionRango, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIntoControlDisciplinario, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntoEstadistica, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnIntoGestionArchivos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );

        lblImagenCobra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelDashboardLayout = new javax.swing.GroupLayout(panelDashboard);
        panelDashboard.setLayout(panelDashboardLayout);
        panelDashboardLayout.setHorizontalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblImagenCobra, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDashboardLayout.setVerticalGroup(
            panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDashboardLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblImagenCobra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIntoAdministracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoAdministracionActionPerformed
        AdministracionInstructores frameAdminInstructores = new AdministracionInstructores();
        frameAdminInstructores.setVisible(true);
    }//GEN-LAST:event_btnIntoAdministracionActionPerformed

    private void btnIntoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoRegistroActionPerformed
        RegistroUsuarioFrame frameRegUsuario = new RegistroUsuarioFrame();
        frameRegUsuario.setVisible(true);
    }//GEN-LAST:event_btnIntoRegistroActionPerformed

    private void btnIntoEvolucionEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoEvolucionEstudianteActionPerformed
        EvolucionEstudiante frameEvolucionEst = new EvolucionEstudiante();
        frameEvolucionEst.setVisible(true);
    }//GEN-LAST:event_btnIntoEvolucionEstudianteActionPerformed

    private void btnIntoPlanificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoPlanificacionActionPerformed
        PlanificacionClases framePlanClases = new PlanificacionClases();
        framePlanClases.setVisible(true);
    }//GEN-LAST:event_btnIntoPlanificacionActionPerformed

    private void btnIntoGestionEspaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoGestionEspaciosActionPerformed
        EspaciosFisicos frameEspaciosF = new EspaciosFisicos();
        frameEspaciosF.setVisible(true);
    }//GEN-LAST:event_btnIntoGestionEspaciosActionPerformed

    private void btnIntoEvaluacionRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoEvaluacionRangoActionPerformed
        EvaluacionRango frameEvaRango = new EvaluacionRango();
        frameEvaRango.setVisible(true);
    }//GEN-LAST:event_btnIntoEvaluacionRangoActionPerformed

    private void btnIntoGestionTorneoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntoGestionTorneoActionPerformed
        Torneo frameTorneo = new Torneo();
        frameTorneo.setVisible(true);
    }//GEN-LAST:event_btnIntoGestionTorneoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InicioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InicioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InicioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InicioDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InicioDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIntoAdministracion;
    private javax.swing.JButton btnIntoControlDisciplinario;
    private javax.swing.JButton btnIntoEstadistica;
    private javax.swing.JButton btnIntoEvaluacionRango;
    private javax.swing.JButton btnIntoEvolucionEstudiante;
    private javax.swing.JButton btnIntoFinanzas;
    private javax.swing.JButton btnIntoGestionArchivos;
    private javax.swing.JButton btnIntoGestionEspacios;
    private javax.swing.JButton btnIntoGestionTorneo;
    private javax.swing.JButton btnIntoPlanificacion;
    private javax.swing.JButton btnIntoRegistro;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagenCobra;
    private javax.swing.JPanel panelDashboard;
    // End of variables declaration//GEN-END:variables
}
